# Generated by Django 5.2.4 on 2025-08-07 09:07

import django.db.models.deletion
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0005_alter_itemmaster_current_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imtrn',
            fields=[
                ('pk', models.CompositePrimaryKey('business_id_id', 'xdocnum', 'xdocrow', 'xsign', blank=True, editable=False, primary_key=True, serialize=False)),
                ('xdocnum', models.CharField(max_length=100)),
                ('token_no', models.CharField(max_length=10)),
                ('xdocrow', models.IntegerField()),
                ('xsign', models.IntegerField()),
                ('xaction', models.CharField(blank=True, max_length=100, null=True)),
                ('xitem', models.CharField(blank=True, max_length=100, null=True)),
                ('xwh', models.CharField(blank=True, max_length=100, null=True)),
                ('xdate', models.DateTimeField(blank=True, null=True)),
                ('xyear', models.IntegerField(blank=True, null=True)),
                ('xper', models.IntegerField(blank=True, null=True)),
                ('xqty', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('xval', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('xvalpost', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('xnote', models.CharField(blank=True, max_length=250, null=True)),
                ('xdoctype', models.CharField(blank=True, max_length=100, null=True)),
                ('xproj', models.CharField(blank=True, max_length=100, null=True)),
                ('xunit', models.CharField(blank=True, max_length=100, null=True)),
                ('xfloor', models.CharField(blank=True, max_length=100, null=True)),
                ('xpocket', models.CharField(blank=True, max_length=100, null=True)),
                ('xbatch', models.CharField(blank=True, max_length=100, null=True)),
                ('xtime', models.DateTimeField(blank=True, null=True)),
                ('xtrnim', models.CharField(blank=True, max_length=10, null=True)),
                ('xbin', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imtrn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('token_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('xmobile', models.CharField(blank=True, max_length=20, null=True)),
                ('xunit', models.CharField(blank=True, max_length=100, null=True)),
                ('xfloor', models.CharField(blank=True, max_length=100, null=True)),
                ('xpocket', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_sacks', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imtor',
            fields=[
                ('create_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('business_id_id', 'ximtor', blank=True, editable=False, primary_key=True, serialize=False)),
                ('ximtor', models.CharField(default=inventory.models.Imtor.generate_transfer_number, max_length=100)),
                ('token_no', models.CharField(max_length=10)),
                ('xtype', models.CharField(max_length=100)),
                ('xfunit', models.CharField(blank=True, max_length=100, null=True)),
                ('xffloor', models.CharField(blank=True, max_length=100, null=True)),
                ('xfpocket', models.CharField(blank=True, max_length=100, null=True)),
                ('xtunit', models.CharField(blank=True, max_length=100, null=True)),
                ('xtfloor', models.CharField(blank=True, max_length=100, null=True)),
                ('xtpocket', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_sacks', models.IntegerField()),
                ('xstatus', models.CharField(blank=True, max_length=100, null=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
