# Generated by Django 5.2.4 on 2025-08-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imtor',
            options={'verbose_name': 'Transfer Order', 'verbose_name_plural': 'Transfer Orders'},
        ),
        migrations.AlterModelTable(
            name='imtor',
            table='imtor',
        ),
    ]
