# Generated by Django 5.2.4 on 2025-07-29 17:26

import django.db.models.deletion
import masterdata.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('address', models.TextField()),
                ('xphone', models.CharField(blank=True, max_length=20)),
                ('xemail', models.EmailField(blank=True, max_length=254)),
                ('xwebsite', models.URLField(blank=True, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_created_profiles', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_updated_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'db_table': 'company_profile',
            },
        ),
        migrations.CreateModel(
            name='CommonCodes',
            fields=[
                ('create_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('business_id', 'xtype', 'xcode', blank=True, editable=False, primary_key=True, serialize=False)),
                ('xtype', models.CharField(max_length=100)),
                ('xcode', models.TextField(max_length=200)),
                ('xdesc', models.TextField(blank=True, max_length=250, null=True)),
                ('xremark', models.TextField(blank=True, max_length=100, null=True)),
                ('zactive', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.companyprofile')),
            ],
            options={
                'verbose_name': 'Common Code',
                'verbose_name_plural': 'Common Codes',
                'db_table': 'commoncodes',
            },
        ),
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('pk', models.CompositePrimaryKey('business_id', 'division_name', 'district_name', 'upazila_name', 'union_name', blank=True, editable=False, primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=100)),
                ('division_bn', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('district_bn', models.CharField(max_length=100)),
                ('upazila_name', models.CharField(max_length=100)),
                ('upazila_bn', models.CharField(max_length=100)),
                ('union_name', models.CharField(max_length=100)),
                ('union_bn', models.CharField(max_length=100)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.companyprofile')),
            ],
            options={
                'verbose_name': 'Geo Location',
                'verbose_name_plural': 'Geo Locations',
                'db_table': 'geo_locations',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('create_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('business_id', 'customer_code', blank=True, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(default=masterdata.models.cus_code, max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('xphone', models.CharField(blank=True, max_length=20, null=True)),
                ('xmobile', models.CharField(blank=True, max_length=20, null=True)),
                ('xemail', models.EmailField(blank=True, max_length=254, null=True)),
                ('xwebsite', models.URLField(blank=True, null=True)),
                ('father_name', models.TextField(blank=True, max_length=100, null=True)),
                ('district_name', models.TextField(blank=True, max_length=100, null=True)),
                ('upazila_name', models.TextField(blank=True, max_length=100, null=True)),
                ('union_name', models.TextField(blank=True, max_length=100, null=True)),
                ('village', models.TextField(blank=True, max_length=100, null=True)),
                ('post_office', models.TextField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('xaddress', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit_terms_days', models.PositiveIntegerField(blank=True, null=True)),
                ('default_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('customer_type', models.CharField(choices=[('Farmer', 'Farmer'), ('Retailer', 'Retailer'), ('Dealer', 'Dealer'), ('Corporate', 'Corporate'), ('Trader', 'Trader'), ('Agent', 'Agent')], default='Farmer', max_length=50)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'db_table': 'customer_profile',
                'ordering': ['customer_code'],
                'indexes': [models.Index(fields=['business_id', 'customer_code', 'xmobile'], name='customer_pr_busines_0f808c_idx')],
                'unique_together': {('business_id', 'customer_code', 'xmobile')},
            },
        ),
    ]
