# Generated by Django 5.2.4 on 2025-07-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='district_bn',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='division_bn',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='union_bn',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='upazila_bn',
            field=models.TextField(max_length=100),
        ),
    ]
