# Generated by Django 5.2.4 on 2025-07-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_alter_geolocation_district_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='division_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
