# Generated by Django 5.2.4 on 2025-08-05 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_customerprofile_division_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('create_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('business_id', 'xitem', blank=True, editable=False, primary_key=True, serialize=False)),
                ('xitem', models.CharField(max_length=50, verbose_name='Item Code')),
                ('xname', models.CharField(max_length=200, verbose_name='Item Name')),
                ('xdesc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('xstype', models.TextField(default='Stock', verbose_name='Stock Type')),
                ('xhscode', models.TextField(blank=True, null=True, verbose_name='H.S. Code')),
                ('xsku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('xbarcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode')),
                ('xgroup', models.CharField(default='FG', max_length=50, verbose_name='Item Group')),
                ('xclass', models.CharField(default='FG', max_length=50, verbose_name='Item Class')),
                ('xcategory', models.CharField(default='FG', max_length=50, verbose_name='Item Category')),
                ('xtype', models.CharField(blank=True, default='FG', max_length=50, null=True, verbose_name='Item Type')),
                ('xbrand', models.CharField(blank=True, default='FG', max_length=100, null=True, verbose_name='Brand')),
                ('xunitpur', models.CharField(default='KG', max_length=50, verbose_name='Purchase Unit')),
                ('xunitstk', models.CharField(default='KG', max_length=50, verbose_name='Stock Unit')),
                ('xunitsel', models.CharField(default='KG', max_length=50, verbose_name='Selling Unit')),
                ('xunitpck', models.CharField(default='KG', max_length=50, verbose_name='Packaging Unit')),
                ('xunitiss', models.CharField(default='KG', max_length=50, verbose_name='Issue Unit')),
                ('xcfpur', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Conversion factor Purchase')),
                ('xcfsta', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Conversion factor Stock')),
                ('xcfsel', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Conversion factor selling')),
                ('xcfpck', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Conversion factor Packaging')),
                ('xcfiss', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Conversion factor Issue')),
                ('xpurprice', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Purchase Price')),
                ('xselprice', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Sales Price')),
                ('current_stock', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Current Stock')),
                ('reorder_level', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Reorder Level')),
                ('max_stock', models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Maximum Stock')),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('shelf_location', models.CharField(blank=True, max_length=100, null=True)),
                ('ledger_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Master',
                'verbose_name_plural': 'Item Masters',
                'db_table': 'item_master',
            },
        ),
    ]
