# Generated by Django 5.2.4 on 2025-08-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_itemmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='current_stock',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='Current Stock'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='max_stock',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='Maximum Stock'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='Reorder Level'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xcfiss',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='Conversion factor Issue'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xcfpck',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='Conversion factor Packaging'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xcfpur',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='Conversion factor Purchase'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xcfsel',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='Conversion factor selling'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xcfsta',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='Conversion factor Stock'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xpurprice',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xselprice',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True, verbose_name='Sales Price'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xunitiss',
            field=models.CharField(blank=True, default='KG', max_length=50, null=True, verbose_name='Issue Unit'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xunitpck',
            field=models.CharField(blank=True, default='KG', max_length=50, null=True, verbose_name='Packaging Unit'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xunitpur',
            field=models.CharField(blank=True, default='KG', max_length=50, null=True, verbose_name='Purchase Unit'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xunitsel',
            field=models.CharField(blank=True, default='KG', max_length=50, null=True, verbose_name='Selling Unit'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='xunitstk',
            field=models.CharField(blank=True, default='KG', max_length=50, null=True, verbose_name='Stock Unit'),
        ),
    ]
