# Generated by Django 5.2.4 on 2025-10-13 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_alter_itemmaster_current_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSetup',
            fields=[
                ('create_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('business_id', 'xyear', 'xtype', blank=True, editable=False, primary_key=True, serialize=False)),
                ('xyear', models.IntegerField()),
                ('xtype', models.CharField(choices=[('RENT_PER_SACK', 'Store Rent'), ('TRANSPORT_CHARGE', 'Transport Charge'), ('FANNING_CHARGE', 'Fanning Charge'), ('LOADING_CHARGE', 'Loading Charge'), ('UNLOADING_CHARGE', 'Unloading Charge')], max_length=50)),
                ('xrate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Master',
                'verbose_name_plural': 'Item Masters',
                'db_table': 'rate_setup',
            },
        ),
    ]
