# Generated by Django 5.2.4 on 2025-07-29 17:27

import django.db.models.deletion
import ops.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('create_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('business_id', 'booking_no', blank=True, editable=False, primary_key=True, serialize=False)),
                ('booking_no', models.CharField(default=ops.models.booking_no, max_length=50)),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.TextField(blank=True, max_length=100, null=True)),
                ('district_name', models.TextField(blank=True, max_length=100, null=True)),
                ('upazila_name', models.TextField(blank=True, max_length=100, null=True)),
                ('union_name', models.TextField(blank=True, max_length=100, null=True)),
                ('village', models.TextField(blank=True, max_length=100, null=True)),
                ('post_office', models.TextField(blank=True, max_length=100, null=True)),
                ('xadvance', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('xsack', models.IntegerField(default=0.0)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='TokenNumber',
            fields=[
                ('create_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('business_id', 'token_no', blank=True, editable=False, primary_key=True, serialize=False)),
                ('token_no', models.IntegerField(default=ops.models.token_no)),
                ('xsack', models.IntegerField(default=0.0)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Number',
                'verbose_name_plural': 'Token Numbers',
                'db_table': 'token_number',
            },
        ),
    ]
