# Generated by Django 5.2.4 on 2025-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokennumber',
            name='token_no',
            field=models.CharField(max_length=10),
        ),
    ]
