# Generated by Django 5.2.4 on 2025-07-29 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_alter_tokennumber_token_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokennumber',
            name='xstatus',
            field=models.CharField(default=datetime.datetime(2025, 7, 29, 17, 43, 0, 810101, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
