# Generated by Django 5.2.4 on 2025-07-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_tokennumber_xstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='division_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tokennumber',
            name='xstatus',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
