# Generated by Django 5.2.4 on 2025-07-31 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_booking_division_name_alter_tokennumber_xstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='xmobile',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi mobile number (e.g. 017XXXXXXXX).', regex='^01[3-9]\\d{8}$')]),
        ),
    ]
