# Generated by Django 5.2.4 on 2025-07-31 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_booking_xmobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='xmobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi mobile number (e.g. 017XXXXXXXX).', regex='^01[3-9]\\d{8}$')]),
        ),
    ]
