# Generated by Django 5.2.4 on 2025-07-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_alter_booking_xmobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='xname',
            field=models.TextField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
