# Generated by Django 5.2.4 on 2025-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_booking_xname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('pk', models.CompositePrimaryKey('business_id', 'token_no', blank=True, editable=False, primary_key=True, serialize=False)),
                ('token_no', models.CharField(max_length=10)),
                ('certificate_no', models.CharField(blank=True, max_length=20, null=True)),
                ('booking_no', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('xmobile', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('division_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upazila_name', models.CharField(blank=True, max_length=100, null=True)),
                ('union_name', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=150, null=True)),
                ('post_office', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_sacks', models.IntegerField()),
                ('potato_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rent_per_sack', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('advance_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remaining_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('number_of_empty_sacks', models.IntegerField()),
                ('price_of_empty_sacks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transportation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('given_loan', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_amount_taka', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certificate',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='xstatus',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
